spring.application.name=films-wish-list-service

spring.jpa.hibernate.ddl-auto=validate
spring.data.jdbc.dialect=postgresql

spring.profiles.active=dev,api,oauth

server.servlet.encoding.force=true

spring.cache.type=redis

spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.host=${REDIS_HORT:localhost}

spring.data.redis.repositories.enabled=false

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

notification.telegram.bot-token=${BOT_TOKEN:1231}

spring.kafka.bootstrap-servers=${kafka_bootstrap_servers:localhost:29092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer