spring.application.name=films-wish-list-service

spring.jpa.hibernate.ddl-auto=validate
spring.data.jdbc.dialect=postgresql

spring.profiles.active=dev,api,oauth

server.servlet.encoding.force=true

spring.cache.type=redis
spring.data.redis.repositories.enabled=false

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

notification.telegram.bot-token=${BOT_TOKEN}